
export const frases = [
    "A sorte favorece os audazes.",
    "Grandes oportunidades esperam por você no futuro.",
    "Seja paciente e persistente em seus objetivos.",
    "A criatividade leva a soluções inovadoras.",
    "Acredite em si mesmo e nos seus sonhos.",
    "A gratidão é a chave para a felicidade.",
    "Sua determinação levará ao sucesso.",
    "Aproveite as pequenas coisas da vida.",
    "A vida é cheia de surpresas maravilhosas.",
    "Aja com gentileza e receba gentileza em troca.",
    "O amor e a amizade são tesouros preciosos.",
    "Seja corajoso em suas decisões.",
    "Você é mais forte do que imagina.",
    "Mantenha uma mente aberta e explore novas possibilidades.",
    "O aprendizado é uma jornada sem fim.",
    "O sucesso está ao virar da esquina.",
    "A sorte está do seu lado hoje.",
    "Aja com bondade e generosidade.",
    "Aprenda com seus erros e cresça.",
    "A perseverança é a chave para superar desafios.",
    "Siga seus sonhos com paixão.",
    "A vida é uma aventura emocionante.",
    "Mantenha-se positivo, mesmo nas dificuldades.",
    "Confie em seu instinto.",
    "A boa sorte está a caminho.",
    "Você é capaz de alcançar grandes coisas.",
    "A felicidade está dentro de você.",
    "O sucesso começa com a determinação.",
    "Este é o momento de brilhar.",
    "Sua criatividade é uma força poderosa.",
    "A sorte acompanha os que trabalham duro.",
    "Aja com sabedoria em suas decisões.",
    "A generosidade traz recompensas inesperadas.",
    "Acredite nos seus sonhos e siga em frente.",
    "A perseverança leva ao triunfo.",
    "Grandes coisas estão a caminho.",
    "Sua paixão o levará longe na vida.",
    "Aprenda com o passado e viva o presente.",
    "A alegria está em todas as pequenas coisas.",
    "Mantenha-se focado em seus objetivos.",
    "A sorte sorri para os que se esforçam.",
    "O amor é a chave para a felicidade.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A gentileza é uma virtude poderosa.",
    "A vida é cheia de oportunidades.",
    "Acredite na sua capacidade de superar desafios.",
    "A sorte está ao seu lado.",
    "Mantenha a mente aberta para novas ideias.",
    "A felicidade está nas pequenas coisas.",
    "A determinação é o segredo do sucesso.",
    "Grandes realizações aguardam você.",
    "A sorte está prestes a mudar sua vida.",
    "Seja grato por cada dia.",
    "A confiança é a chave para o progresso.",
    "Aja com coragem e ousadia.",
    "A criatividade é o combustível da inovação.",
    "Você é a luz no fim do túnel.",
    "O sucesso está a um passo de distância.",
    "A paciência leva à vitória.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação.",
    "Mantenha uma visão clara de seus objetivos.",
    "A determinação é o caminho para o triunfo.",
    "Acredite nas possibilidades infinitas.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está prestes a mudar sua vida.",
    "Você é a luz no fim do túnel.",
    "O sucesso está ao seu alcance.",
    "A paciência leva à realização dos sonhos.",
    "A sabedoria é a chave para o crescimento.",
    "A generosidade traz riqueza espiritual.",
    "Acredite nos seus sonhos e siga em frente.",
    "Siga sua intuição; ela o guiará bem.",
    "A sorte está a caminho.",
    "Você tem a força para superar qualquer obstáculo.",
    "A felicidade está ao seu alcance.",
    "A perseverança é o segredo do progresso.",
    "Este é o dia de transformar sonhos em realidade.",
    "Sua paixão o levará a lugares incríveis.",
    "Aprenda com o passado e olhe para o futuro.",
    "A vida é uma jornada emocionante.",
    "Mantenha um coração aberto e uma mente aberta.",
    "A gentileza é uma virtude poderosa.",
    "A sorte está do seu lado hoje.",
    "O amor é a essência da vida.",
    "A coragem leva a conquistas extraordinárias.",
    "Você está no caminho certo para o sucesso.",
    "A sabedoria vem com a experiência.",
    "A confiança em si mesmo é fundamental.",
    "Grandes coisas estão reservadas para você.",
    "A sorte sorri para os que trabalham com dedicação."
]